
CREATE OR REPLACE VIEW ANALYTICS.CUSTOMER_ORDER_SUMMARY AS
SELECT
    C.CUSTOMER_ID,
    C.FIRST_NAME,
    C.LAST_NAME,
    COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
    SUM(O.FINAL_AMOUNT) AS TOTAL_SPEND,
    AVG(O.FINAL_AMOUNT) AS AVG_ORDER_VALUE
FROM MASTER.CUSTOMERS C
LEFT JOIN TRANSACTIONAL.ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY 1,2,3;
