
CREATE OR REPLACE TABLE MASTER.CUSTOMERS_BASE (
    CUSTOMER_ID NUMBER,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    GENDER STRING,
    DATE_OF_BIRTH DATE,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    PINCODE STRING,
    CUSTOMER_SEGMENT STRING,
    REGISTERED_DATE DATE,
    IS_ACTIVE BOOLEAN
);