
CREATE OR REPLACE TABLE MASTER.PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME STRING,
    CATEGORY_ID NUMBER,
    SUPPLIER_ID NUMBER,
    BRAND STRING,
    UNIT_PRICE NUMBER(10,2),
    COST_PRICE NUMBER(10,2),
    STOCK_QUANTITY NUMBER,
    SKU STRING,
    PRODUCT_STATUS STRING,
    CREATED_AT TIMESTAMP
);