
CREATE OR REPLACE TABLE TRANSACTIONAL.ORDERS (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    STORE_ID NUMBER,
    ORDER_DATE TIMESTAMP,
    ORDER_STATUS STRING,
    PAYMENT_STATUS STRING,
    SHIPPING_ADDRESS STRING,
    TOTAL_AMOUNT NUMBER(10,2),
    DISCOUNT_AMOUNT NUMBER(10,2),
    TAX_AMOUNT NUMBER(10,2),
    FINAL_AMOUNT NUMBER(10,2)
);