
CREATE OR REPLACE TABLE TRANSACTIONAL.PAYMENTS (
    PAYMENT_ID NUMBER,
    ORDER_ID NUMBER,
    PAYMENT_METHOD STRING,
    PAYMENT_DATE TIMESTAMP,
    PAYMENT_AMOUNT NUMBER(10,2),
    PAYMENT_STATUS STRING,
    TRANSACTION_REFERENCE STRING
);