
CREATE OR REPLACE TABLE TRANSACTIONAL.ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER,
    ORDER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    UNIT_PRICE NUMBER(10,2),
    TOTAL_PRICE NUMBER(10,2)
);