
CREATE OR REPLACE TABLE TRANSACTIONAL.INVENTORY (
    INVENTORY_ID NUMBER,
    PRODUCT_ID NUMBER,
    STORE_ID NUMBER,
    AVAILABLE_QUANTITY NUMBER,
    RESERVED_QUANTITY NUMBER,
    LAST_UPDATED TIMESTAMP
);